id: PYSEC-2021-59
package:
  name: urllib3
  ecosystem: PyPI
summary: Vulnerability in urllib3
details: The urllib3 library 1.26.x before 1.26.4 for Python omits SSL certificate
  validation in some cases involving HTTPS to HTTPS proxies. The initial connection
  to the HTTPS proxy (if an SSLContext isn't given via proxy_config) doesn't verify
  the hostname of the certificate. This means certificates for different servers that
  still validate properly with the default urllib3 SSLContext will be silently accepted.
affects:
  ranges:
  - type: GIT
    repo: https://github.com/urllib3/urllib3
    fixed: 8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0
  - type: ECOSYSTEM
    introduced: 1.26.0
    fixed: 1.26.4
references:
- type: WEB
  url: https://github.com/urllib3/urllib3/commits/main
- type: WEB
  url: https://pypi.org/project/urllib3/1.26.4/
- type: WEB
  url: https://github.com/urllib3/urllib3/commit/8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0
- type: WEB
  url: https://github.com/urllib3/urllib3/security/advisories/GHSA-5phf-pp7p-vc2r
aliases:
- CVE-2021-28363
modified: "2021-03-23T16:47:00Z"
published: "2021-03-15T18:15:00Z"
